sonata_admin:

    templates:
        # default global templates
        layout:  SonataAdminBundle::layout.html.twig

    dashboard:
        blocks:
            -
                position: top
                class: hidden
                type: sonata.admin.block.admin_list

        groups:
            sonata.admin.crawler:
                label: Crawler
                icon: '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.admin.crawler
                    # - sonata.admin.groups

sonata_user:
    security_acl: true
    manager_type: orm

    class:                  # Entity Classes
        user:               LoopAnime\UserBundle\Entity\User
        group:              FOS\UserBundle\Entity\Group

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        # Your other blocks

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions